# Generated by Django 2.0.5 on 2018-06-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=512, null=True)),
                ('message', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roll_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_Num', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='accessrec',
            name='RollNumber',
            field=models.ForeignKey(null=True, on_delete='', to='AppOne.Roll_Number'),
        ),
    ]
